# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: access_token_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("access_token_request.proto", :syntax => :proto3) do
    add_message "tokopedia.AccessTokenRequest" do
      optional :client_id, :string, 1
      optional :client_secret, :string, 2
    end
  end
end

module Tokopedia
  AccessTokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.AccessTokenRequest").msgclass
end
