# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_request.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order_request.proto", :syntax => :proto3) do
    add_message "tokopedia.OrderRequest" do
      optional :fs_id, :uint64, 1
      optional :order_id, :uint64, 2
      optional :access_token, :string, 3
    end
  end
end

module Tokopedia
  OrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.OrderRequest").msgclass
end
