# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order.proto", :syntax => :proto3) do
    add_message "tokopedia.Order" do
      optional :data, :message, 1, "tokopedia.Order.Data"
    end
    add_message "tokopedia.Order.Data" do
      optional :order_id, :uint64, 1
      optional :invoice_number, :string, 2
      optional :order_info, :message, 3, "tokopedia.Order.Data.OrderInfo"
      optional :create_time, :string, 4
      optional :shipment_fulfillment, :message, 5, "tokopedia.Order.Data.ShipmentFulfillment"
      optional :buyer_info, :message, 6, "tokopedia.Order.Data.BuyerInfo"
      optional :order_warehouse, :message, 7, "tokopedia.Order.Data.OrderWarehouse"
      optional :order_status, :uint64, 8
      optional :payment_info, :message, 9, "tokopedia.Order.Data.PaymentInfo"
    end
    add_message "tokopedia.Order.Data.PaymentInfo" do
      optional :gateway_name, :string, 1
    end
    add_message "tokopedia.Order.Data.OrderWarehouse" do
      optional :warehouse_id, :uint64, 1
      optional :fulfill_by, :uint64, 2
    end
    add_message "tokopedia.Order.Data.BuyerInfo" do
      optional :buyer_phone, :string, 1
    end
    add_message "tokopedia.Order.Data.OrderInfo" do
      optional :destination, :message, 1, "tokopedia.Order.Data.OrderInfo.Destination"
      optional :shipping_info, :message, 2, "tokopedia.Order.Data.OrderInfo.ShippingInfo"
      repeated :order_detail, :message, 3, "tokopedia.Order.Data.OrderInfo.OrderDetail"
    end
    add_message "tokopedia.Order.Data.OrderInfo.OrderDetail" do
      optional :product_id, :uint64, 1
      optional :product_name, :string, 2
      optional :product_price, :uint64, 3
      optional :quantity, :uint32, 4
      optional :quantity_deliver, :uint32, 5
      optional :quantity_reject, :uint32, 6
    end
    add_message "tokopedia.Order.Data.OrderInfo.ShippingInfo" do
      optional :logistic_name, :string, 1
      optional :logistic_service, :string, 2
      optional :shipping_price, :uint64, 3
      optional :second_insurance, :uint64, 4
      optional :awb, :string, 5
      optional :insurance_price, :uint64, 6
    end
    add_message "tokopedia.Order.Data.OrderInfo.Destination" do
      optional :receiver_name, :string, 1
      optional :address_street, :string, 2
      optional :address_city, :string, 3
      optional :address_province, :string, 4
      optional :address_postal, :string, 5
      optional :receiver_phone, :string, 6
    end
    add_message "tokopedia.Order.Data.ShipmentFulfillment" do
      optional :payment_date_time, :string, 1
    end
  end
end

module Tokopedia
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order").msgclass
  Order::Data = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data").msgclass
  Order::Data::PaymentInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.PaymentInfo").msgclass
  Order::Data::OrderWarehouse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.OrderWarehouse").msgclass
  Order::Data::BuyerInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.BuyerInfo").msgclass
  Order::Data::OrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.OrderInfo").msgclass
  Order::Data::OrderInfo::OrderDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.OrderInfo.OrderDetail").msgclass
  Order::Data::OrderInfo::ShippingInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.OrderInfo.ShippingInfo").msgclass
  Order::Data::OrderInfo::Destination = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.OrderInfo.Destination").msgclass
  Order::Data::ShipmentFulfillment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("tokopedia.Order.Data.ShipmentFulfillment").msgclass
end
