# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

require 'access_token_request_pb'
require 'access_token_pb'
require 'order_pb'
require 'order_request_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service.proto", :syntax => :proto3) do
  end
end

module Tokopedia
end
