# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service.proto for package 'tokopedia'

require 'grpc'
require 'service_pb'

module Tokopedia
  module Service
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'tokopedia.Service'

      rpc :GetAccessToken, ::Tokopedia::AccessTokenRequest, ::Tokopedia::AccessToken
      rpc :GetOrder, ::Tokopedia::OrderRequest, ::Tokopedia::Order
    end

    Stub = Service.rpc_stub_class
  end
end
