// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: order.proto

package tokopedia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *Order_Data `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Order) Reset() {
	*x = Order{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetData() *Order_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Order_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId             uint64                          `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	InvoiceNumber       string                          `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Order               *Order_Data_OrderInfo           `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	CreateTime          string                          `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ShipmentFulfillment *Order_Data_ShipmentFulfillment `protobuf:"bytes,5,opt,name=shipment_fulfillment,json=shipmentFulfillment,proto3" json:"shipment_fulfillment,omitempty"`
	BuyerInfo           *Order_Data_BuyerInfo           `protobuf:"bytes,6,opt,name=buyer_info,json=buyerInfo,proto3" json:"buyer_info,omitempty"`
	OrderWarehouse      *Order_Data_OrderWarehouse      `protobuf:"bytes,7,opt,name=order_warehouse,json=orderWarehouse,proto3" json:"order_warehouse,omitempty"`
	OrderStatus         uint64                          `protobuf:"varint,8,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentInfo         *Order_Data_PaymentInfo         `protobuf:"bytes,9,opt,name=payment_info,json=paymentInfo,proto3" json:"payment_info,omitempty"`
}

func (x *Order_Data) Reset() {
	*x = Order_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data) ProtoMessage() {}

func (x *Order_Data) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data.ProtoReflect.Descriptor instead.
func (*Order_Data) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Order_Data) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order_Data) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *Order_Data) GetOrder() *Order_Data_OrderInfo {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *Order_Data) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *Order_Data) GetShipmentFulfillment() *Order_Data_ShipmentFulfillment {
	if x != nil {
		return x.ShipmentFulfillment
	}
	return nil
}

func (x *Order_Data) GetBuyerInfo() *Order_Data_BuyerInfo {
	if x != nil {
		return x.BuyerInfo
	}
	return nil
}

func (x *Order_Data) GetOrderWarehouse() *Order_Data_OrderWarehouse {
	if x != nil {
		return x.OrderWarehouse
	}
	return nil
}

func (x *Order_Data) GetOrderStatus() uint64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *Order_Data) GetPaymentInfo() *Order_Data_PaymentInfo {
	if x != nil {
		return x.PaymentInfo
	}
	return nil
}

type Order_Data_PaymentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayName string `protobuf:"bytes,1,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
}

func (x *Order_Data_PaymentInfo) Reset() {
	*x = Order_Data_PaymentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_PaymentInfo) ProtoMessage() {}

func (x *Order_Data_PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_PaymentInfo.ProtoReflect.Descriptor instead.
func (*Order_Data_PaymentInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Order_Data_PaymentInfo) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

type Order_Data_OrderWarehouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WarehouseId uint64 `protobuf:"varint,1,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	FulfillBy   uint64 `protobuf:"varint,2,opt,name=fulfill_by,json=fulfillBy,proto3" json:"fulfill_by,omitempty"`
}

func (x *Order_Data_OrderWarehouse) Reset() {
	*x = Order_Data_OrderWarehouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_OrderWarehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_OrderWarehouse) ProtoMessage() {}

func (x *Order_Data_OrderWarehouse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_OrderWarehouse.ProtoReflect.Descriptor instead.
func (*Order_Data_OrderWarehouse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Order_Data_OrderWarehouse) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *Order_Data_OrderWarehouse) GetFulfillBy() uint64 {
	if x != nil {
		return x.FulfillBy
	}
	return 0
}

type Order_Data_BuyerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuyerEmail string `protobuf:"bytes,1,opt,name=buyer_email,json=buyerEmail,proto3" json:"buyer_email,omitempty"`
}

func (x *Order_Data_BuyerInfo) Reset() {
	*x = Order_Data_BuyerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_BuyerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_BuyerInfo) ProtoMessage() {}

func (x *Order_Data_BuyerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_BuyerInfo.ProtoReflect.Descriptor instead.
func (*Order_Data_BuyerInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 2}
}

func (x *Order_Data_BuyerInfo) GetBuyerEmail() string {
	if x != nil {
		return x.BuyerEmail
	}
	return ""
}

type Order_Data_OrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShippingPrice   uint64                              `protobuf:"varint,1,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	SecondInsurance uint64                              `protobuf:"varint,2,opt,name=second_insurance,json=secondInsurance,proto3" json:"second_insurance,omitempty"`
	Destination     *Order_Data_OrderInfo_Destination   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	ShippingInfo    *Order_Data_OrderInfo_ShippingInfo  `protobuf:"bytes,4,opt,name=shipping_info,json=shippingInfo,proto3" json:"shipping_info,omitempty"`
	OrderDetail     []*Order_Data_OrderInfo_OrderDetail `protobuf:"bytes,5,rep,name=order_detail,json=orderDetail,proto3" json:"order_detail,omitempty"`
}

func (x *Order_Data_OrderInfo) Reset() {
	*x = Order_Data_OrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_OrderInfo) ProtoMessage() {}

func (x *Order_Data_OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_OrderInfo.ProtoReflect.Descriptor instead.
func (*Order_Data_OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 3}
}

func (x *Order_Data_OrderInfo) GetShippingPrice() uint64 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *Order_Data_OrderInfo) GetSecondInsurance() uint64 {
	if x != nil {
		return x.SecondInsurance
	}
	return 0
}

func (x *Order_Data_OrderInfo) GetDestination() *Order_Data_OrderInfo_Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Order_Data_OrderInfo) GetShippingInfo() *Order_Data_OrderInfo_ShippingInfo {
	if x != nil {
		return x.ShippingInfo
	}
	return nil
}

func (x *Order_Data_OrderInfo) GetOrderDetail() []*Order_Data_OrderInfo_OrderDetail {
	if x != nil {
		return x.OrderDetail
	}
	return nil
}

type Order_Data_ShipmentFulfillment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentDateTime string `protobuf:"bytes,1,opt,name=payment_date_time,json=paymentDateTime,proto3" json:"payment_date_time,omitempty"`
}

func (x *Order_Data_ShipmentFulfillment) Reset() {
	*x = Order_Data_ShipmentFulfillment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_ShipmentFulfillment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_ShipmentFulfillment) ProtoMessage() {}

func (x *Order_Data_ShipmentFulfillment) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_ShipmentFulfillment.ProtoReflect.Descriptor instead.
func (*Order_Data_ShipmentFulfillment) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 4}
}

func (x *Order_Data_ShipmentFulfillment) GetPaymentDateTime() string {
	if x != nil {
		return x.PaymentDateTime
	}
	return ""
}

type Order_Data_OrderInfo_OrderDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId       uint64 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName     string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductPrice    uint64 `protobuf:"varint,3,opt,name=product_price,json=productPrice,proto3" json:"product_price,omitempty"`
	Quantity        uint32 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	QuantityDeliver uint32 `protobuf:"varint,5,opt,name=quantity_deliver,json=quantityDeliver,proto3" json:"quantity_deliver,omitempty"`
	QuantityReject  uint32 `protobuf:"varint,6,opt,name=quantity_reject,json=quantityReject,proto3" json:"quantity_reject,omitempty"`
}

func (x *Order_Data_OrderInfo_OrderDetail) Reset() {
	*x = Order_Data_OrderInfo_OrderDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_OrderInfo_OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_OrderInfo_OrderDetail) ProtoMessage() {}

func (x *Order_Data_OrderInfo_OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_OrderInfo_OrderDetail.ProtoReflect.Descriptor instead.
func (*Order_Data_OrderInfo_OrderDetail) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 3, 0}
}

func (x *Order_Data_OrderInfo_OrderDetail) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Order_Data_OrderInfo_OrderDetail) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Order_Data_OrderInfo_OrderDetail) GetProductPrice() uint64 {
	if x != nil {
		return x.ProductPrice
	}
	return 0
}

func (x *Order_Data_OrderInfo_OrderDetail) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order_Data_OrderInfo_OrderDetail) GetQuantityDeliver() uint32 {
	if x != nil {
		return x.QuantityDeliver
	}
	return 0
}

func (x *Order_Data_OrderInfo_OrderDetail) GetQuantityReject() uint32 {
	if x != nil {
		return x.QuantityReject
	}
	return 0
}

type Order_Data_OrderInfo_ShippingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogisticName    string `protobuf:"bytes,1,opt,name=logistic_name,json=logisticName,proto3" json:"logistic_name,omitempty"`
	LogisticService string `protobuf:"bytes,2,opt,name=logistic_service,json=logisticService,proto3" json:"logistic_service,omitempty"`
	ShippingPrice   uint64 `protobuf:"varint,3,opt,name=shipping_price,json=shippingPrice,proto3" json:"shipping_price,omitempty"`
	SecondInsurance uint64 `protobuf:"varint,4,opt,name=second_insurance,json=secondInsurance,proto3" json:"second_insurance,omitempty"`
	Awb             string `protobuf:"bytes,5,opt,name=awb,proto3" json:"awb,omitempty"`
}

func (x *Order_Data_OrderInfo_ShippingInfo) Reset() {
	*x = Order_Data_OrderInfo_ShippingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_OrderInfo_ShippingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_OrderInfo_ShippingInfo) ProtoMessage() {}

func (x *Order_Data_OrderInfo_ShippingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_OrderInfo_ShippingInfo.ProtoReflect.Descriptor instead.
func (*Order_Data_OrderInfo_ShippingInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 3, 1}
}

func (x *Order_Data_OrderInfo_ShippingInfo) GetLogisticName() string {
	if x != nil {
		return x.LogisticName
	}
	return ""
}

func (x *Order_Data_OrderInfo_ShippingInfo) GetLogisticService() string {
	if x != nil {
		return x.LogisticService
	}
	return ""
}

func (x *Order_Data_OrderInfo_ShippingInfo) GetShippingPrice() uint64 {
	if x != nil {
		return x.ShippingPrice
	}
	return 0
}

func (x *Order_Data_OrderInfo_ShippingInfo) GetSecondInsurance() uint64 {
	if x != nil {
		return x.SecondInsurance
	}
	return 0
}

func (x *Order_Data_OrderInfo_ShippingInfo) GetAwb() string {
	if x != nil {
		return x.Awb
	}
	return ""
}

type Order_Data_OrderInfo_Destination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverName    string `protobuf:"bytes,1,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	AddressStreet   string `protobuf:"bytes,2,opt,name=address_street,json=addressStreet,proto3" json:"address_street,omitempty"`
	AddressCity     string `protobuf:"bytes,3,opt,name=address_city,json=addressCity,proto3" json:"address_city,omitempty"`
	AddressProvince string `protobuf:"bytes,4,opt,name=address_province,json=addressProvince,proto3" json:"address_province,omitempty"`
	AddressPostal   string `protobuf:"bytes,5,opt,name=address_postal,json=addressPostal,proto3" json:"address_postal,omitempty"`
	ReceiverPhone   string `protobuf:"bytes,6,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
}

func (x *Order_Data_OrderInfo_Destination) Reset() {
	*x = Order_Data_OrderInfo_Destination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Order_Data_OrderInfo_Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Data_OrderInfo_Destination) ProtoMessage() {}

func (x *Order_Data_OrderInfo_Destination) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Data_OrderInfo_Destination.ProtoReflect.Descriptor instead.
func (*Order_Data_OrderInfo_Destination) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 3, 2}
}

func (x *Order_Data_OrderInfo_Destination) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *Order_Data_OrderInfo_Destination) GetAddressStreet() string {
	if x != nil {
		return x.AddressStreet
	}
	return ""
}

func (x *Order_Data_OrderInfo_Destination) GetAddressCity() string {
	if x != nil {
		return x.AddressCity
	}
	return ""
}

func (x *Order_Data_OrderInfo_Destination) GetAddressProvince() string {
	if x != nil {
		return x.AddressProvince
	}
	return ""
}

func (x *Order_Data_OrderInfo_Destination) GetAddressPostal() string {
	if x != nil {
		return x.AddressPostal
	}
	return ""
}

func (x *Order_Data_OrderInfo_Destination) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

var file_order_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74,
	0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x22, 0x98, 0x0e, 0x0a, 0x05, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xe3, 0x0d,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65,
	0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x5c, 0x0a, 0x14, 0x73, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x75, 0x6c,
	0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29,
	0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x75,
	0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x13, 0x73, 0x68, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e,
	0x0a, 0x0a, 0x62, 0x75, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x42, 0x75, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4d,
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65,
	0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x0e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x44, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64,
	0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x30, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x52, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x5f, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x42, 0x79, 0x1a, 0x2c, 0x0a, 0x09,
	0x42, 0x75, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x79,
	0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x75, 0x79, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x1a, 0xf3, 0x07, 0x0a, 0x09, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x29, 0x0a, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x49, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x0d, 0x73, 0x68, 0x69,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2c, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4e, 0x0a, 0x0c,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0xe4, 0x01, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x29, 0x0a, 0x10, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0e, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x6a,
	0x65, 0x63, 0x74, 0x1a, 0xc2, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x68,
	0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x73, 0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x49, 0x6e, 0x73,
	0x75, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x77, 0x62, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x77, 0x62, 0x1a, 0xf5, 0x01, 0x0a, 0x0b, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74,
	0x72, 0x65, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x43, 0x69, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x50, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x1a, 0x41, 0x0a, 0x13, 0x53, 0x68, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x74, 0x6f, 0x6b, 0x6f, 0x70, 0x65, 0x64,
	0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData = file_order_proto_rawDesc
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_proto_rawDescData)
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_order_proto_goTypes = []interface{}{
	(*Order)(nil),                             // 0: tokopedia.Order
	(*Order_Data)(nil),                        // 1: tokopedia.Order.Data
	(*Order_Data_PaymentInfo)(nil),            // 2: tokopedia.Order.Data.PaymentInfo
	(*Order_Data_OrderWarehouse)(nil),         // 3: tokopedia.Order.Data.OrderWarehouse
	(*Order_Data_BuyerInfo)(nil),              // 4: tokopedia.Order.Data.BuyerInfo
	(*Order_Data_OrderInfo)(nil),              // 5: tokopedia.Order.Data.OrderInfo
	(*Order_Data_ShipmentFulfillment)(nil),    // 6: tokopedia.Order.Data.ShipmentFulfillment
	(*Order_Data_OrderInfo_OrderDetail)(nil),  // 7: tokopedia.Order.Data.OrderInfo.OrderDetail
	(*Order_Data_OrderInfo_ShippingInfo)(nil), // 8: tokopedia.Order.Data.OrderInfo.ShippingInfo
	(*Order_Data_OrderInfo_Destination)(nil),  // 9: tokopedia.Order.Data.OrderInfo.Destination
}
var file_order_proto_depIdxs = []int32{
	1, // 0: tokopedia.Order.data:type_name -> tokopedia.Order.Data
	5, // 1: tokopedia.Order.Data.order:type_name -> tokopedia.Order.Data.OrderInfo
	6, // 2: tokopedia.Order.Data.shipment_fulfillment:type_name -> tokopedia.Order.Data.ShipmentFulfillment
	4, // 3: tokopedia.Order.Data.buyer_info:type_name -> tokopedia.Order.Data.BuyerInfo
	3, // 4: tokopedia.Order.Data.order_warehouse:type_name -> tokopedia.Order.Data.OrderWarehouse
	2, // 5: tokopedia.Order.Data.payment_info:type_name -> tokopedia.Order.Data.PaymentInfo
	9, // 6: tokopedia.Order.Data.OrderInfo.destination:type_name -> tokopedia.Order.Data.OrderInfo.Destination
	8, // 7: tokopedia.Order.Data.OrderInfo.shipping_info:type_name -> tokopedia.Order.Data.OrderInfo.ShippingInfo
	7, // 8: tokopedia.Order.Data.OrderInfo.order_detail:type_name -> tokopedia.Order.Data.OrderInfo.OrderDetail
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_PaymentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_OrderWarehouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_BuyerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_OrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_ShipmentFulfillment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_OrderInfo_OrderDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_OrderInfo_ShippingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Order_Data_OrderInfo_Destination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_rawDesc = nil
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
